### ISSUE TITLE
TestFlight App 打开依旧缓慢

### ISSUE THREAD

**Issue by OscarGong** [gongjianhui/AppleDNS#11]
希望支持

**Comment by gongjianhui** [comment]
是这样，TestFlight 在下载 App 时使用了 iosapps.itunes.apple.com 这个域名，然而绝大多数的 TestFlight App 在大陆节点并没有缓存，所以导致无法下载 App，临时的解决方案是：全局代理。

**Comment by gongjianhui** [comment]
如果你在 TestFlight 中下载 Surge 出现了问题.....你可以试试挂非 Surge 的代理软件，或者路由器配置代理。

**Comment by gongjianhui** [comment]
另外刚刚的测试中发现了 beta.itunes.apple.com，马上测试。

**Comment by OscarGong** [comment]
其实影响不大，毕竟 TF 不像 App Store, iTunes Store 一样是需要经常打开的 App
TF 缓慢的时候使用 Anyconnect 就好

感谢您的工作！

**Comment by gongjianhui** [comment]
beta.itunes.apple.com = 23.198.126.94 
你试试
Akamai HK 节点

**Comment by OscarGong** [comment]
另外新建一个 config，删除掉下面项后
upp.itunes.apple.com 
su.itunes.apple.com  
play.itunes.apple.com 
se.itunes.apple.com 
api.itunes.apple.com 
search.itunes.apple.co
osxapps.itunes.apple.com
iosapps.itunes.apple.com
streamingaudio.itunes.com
aod.itunes.apple.com 
appldnld.apple.com 

只保留 beta.itunes.apple.com = 23.198.126.94 

虽然没有直接全局到 HK 快，但是 It Just Work~👍

**Comment by gongjianhui** [comment]
因为 beta.itunes.apple.com 没国内节点，只能找最近的香港。
