### ISSUE TITLE
python 2.7 的版本，不知道有没有效，如果有效请作者合并形成 python2 python3都能用的版本

### ISSUE THREAD

**Issue by jannson** [gongjianhui/AppleDNS#14]
https://github.com/jannson/AppleDNS

依赖 itertools 以及 six

python2 我把多线程的去掉了。反正运行一次，线程应试也问题不大。这样很多像我一样的用户，不需要单独为一个项目去编译与安装一个 python3 的版本。请作者考虑合并下。谢谢。

**Comment by gongjianhui** [comment]
基本没问题，除了去除多线程后的速度。

**Comment by gongjianhui** [comment]
我准备放入 Repo，需要加入什么开源 License 吗，默认 CC0？

**Comment by jannson** [comment]
代码是你的，我就改了一点。想要什么 License 你觉得哪个好就行。
并且我就改一会，未来我也不维护的。你辛苦了。

**Comment by gongjianhui** [comment]
代码不是我的，代码作者要求 CC0，不设任何限制，衍生版本可以自己选择 Licesnse。
既然你没有要求，那我就 CC0 继承了。

**Comment by jannson** [comment]
在论坛里求加个 QQ，私信。未来我来实现 C 语言版本的吧。到时候可能需要请教你，这样我才可以集成到路由器里面。

**Comment by gongjianhui** [comment]
邮件或 iMessage 都是：i&gongjianhui.com
Telegram：@gongjainhui

**Comment by gongjianhui** [comment]
**1. merlin 下单独设置 itunes.apple.com dnsmasq 会导致泛解析异常，你没有看我的文档**

2. 希望能在 Merlin 版本帖子中放入本项目 GitHub 地址以供其他人在此基础开发
3. 数据收集不易，希望可以将 GitHub 中的「求打赏」信息加入 Koolshare.cn Merlin 帖，十分感谢。

**Comment by jannson** [comment]
加阿，我发帖子的时候就已经加入了你的帖子链接，你的帖子有这个项目的链接。在我帖子的最上面，哈哈。
感谢你，辛苦了。
