### ISSUE TITLE
win7 python2.7报错

### ISSUE THREAD

**Issue by sykiewang** [gongjianhui/AppleDNS#17]
C:\Users\Administrator\Desktop\AppleDNS-master>python fetch-timeout-py2.py --pay
load ChinaUnicom.json
Apple Music 音频文件、Mac/iOS App Store 应用
aod.itunes.apple.com, iosapps.itunes.apple.com, osxapps.itunes.apple.com, stream
ingaudio.itunes.apple.com, mvod.itunes.apple.com
Traceback (most recent call last):
  File "fetch-timeout-py2.py", line 104, in <module>
    main()
  File "fetch-timeout-py2.py", line 99, in main
    payload = fetch(json.load(open(args.payload)))
  File "fetch-timeout-py2.py", line 83, in fetch
    ips = itertools.imap(request, map(handle_ip, ips * testing_times))
  File "fetch-timeout-py2.py", line 73, in handle_ip
    from six.moves.urllib.parse import urlparse
ImportError: No module named six.moves.urllib.parse

**Comment by sykiewang** [comment]
需要安装six依赖，安装后正常，导出配置时报错，结果如下：
C:\Users\Administrator\Desktop\AppleDNS-master>python export-configure.py --targ
et surge
Traceback (most recent call last):
  File "export-configure.py", line 52, in <module>
    main()
  File "export-configure.py", line 47, in main
    payload = json.load(open('result.json', encoding='UTF-8'))
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by gongjianhui** [comment]
你先通过安装 Python3 解决。

**Comment by sykiewang** [comment]
好吧，还有，导出的merlin配置怎么使用呢？在路由器的SS选项卡里么？

**Comment by gongjianhui** [comment]
通过 DNSMASQ。

**Comment by gongjianhui** [comment]
我不是这些固件的用户，没法帮你，你可以通过固件社区寻得帮助。

**Comment by sykiewang** [comment]
哦哦。好的

**Comment by jannson** [comment]
/jffs/configs/dnsmasq.d 目录下。

**Comment by sykiewang** [comment]
我靠，我认识你，我用的就是你修改的版本。太激动了！
