### ISSUE TITLE
并不是真正的 issue，更像是吐槽

### ISSUE THREAD

**Issue by ibegyourpardon** [gongjianhui/AppleDNS#2]
你说 Apple 家的 CDN 网络全不全，全，当然全，国内外都有。
Store 用起来慢不慢，慢，当然慢。
赖不赖国际出口，当然赖。

但是——

就算在国外，北美，照样有人翻着白眼吐槽卡的要死，动不动白屏。

所以我很怀疑只通过搜集 IP 的方法到底能提高多少速度。

尤其是——Apple 家的问题有的时候很独特，看人品，有的人就死活说我快的不行，有的人就硬是慢到飞起。拿我来说，同样是上海电信，我在这个朋友家直连美区也快，到另外个朋友家就只能翻白眼。

**Comment by magicdawn** [comment]
Apple说: 怪我喽 :joy: 
另: 这三个 json 怎么搜集的？
