### ISSUE TITLE
教育网？

### ISSUE THREAD

**Issue by xplorld** [gongjianhui/AppleDNS#20]
教育网选哪个？

**Comment by Zhang-Chinese** [comment]
教育网出错。。。
![image](https://cloud.githubusercontent.com/assets/18135204/14099733/ad0bf7e4-f5ba-11e5-8a27-8d4503c55263.png)

**Comment by gongjianhui** [comment]
你需要安装 six
一般情况下执行
pip install six
即可，如遇问题请自行 Google。
