### ISSUE TITLE
联通线路，IP不可用

### ISSUE THREAD

**Issue by iwater** [gongjianhui/AppleDNS#28]
使用生成的hosts文件，itunes都打不开，也无法下载

**Comment by gongjianhui** [comment]
IP 不可用的问题暂时不好解决，你先去掉 hosts 吧。

**Comment by w201603** [comment]
![koala](https://cloud.githubusercontent.com/assets/18158099/14133536/b2e2424a-f682-11e5-976e-58b643288360.jpg)

**Comment by septs** [comment]
请尝试新的脚本
