### ISSUE TITLE
对封了ping的校园网，有别的方法检测么？

### ISSUE THREAD

**Issue by galaxy001** [gongjianhui/AppleDNS#32]
校园网封了ICMP，ping没法返回。
可以用HTTP的方法么？比如访问某个app的介绍页图片资源。

**Comment by gongjianhui** [comment]
你可以通过威胁校园网机房管理人员的方式来获取 Ping 结果。

**Comment by septs** [comment]
try for http://www.elifulkerson.com/projects/tcping.php
