### ISSUE TITLE
Script raise exception on OpenWRT ash

### ISSUE THREAD

**Issue by AustinChou** [gongjianhui/AppleDNS#33]
I've installed git and python package on my router running OpenWRT 14.07. After I clone the script and start running, the exception is raised. 

```
UnicodeEncodeError: 'ascii' codec can't encode characters in position xx-xx: ordinal not in range(128)
```

This is related to the output system in OpenWRT, and may caused by a defect in OpenWRT's localized environment. So I strongly recommend replace Chinese characters with English instead to fix this problem. The typical use case of this is that I can run a daily task detecting my best Apple DNS choices based on my network and write the host results to my router's host file. 

Also, some one has mention the same issue before but not in this repository: https://github.com/houtianze/bypy/issues/11

**Comment by rampageX** [comment]
https://github.com/gongjianhui/AppleDNS/pull/34
