### ISSUE TITLE
Merlin & 北京联通，生成后无法下载应用

### ISSUE THREAD

**Issue by yt1988** [gongjianhui/AppleDNS#35]
RT

生成了 Merlin 版本，加入自定义 DNSMASQ。

之后出现App Store应用无法正常下载，不知道是哪里的问题。

**Comment by fisherwei** [comment]
北京联通

无法从 IOS app store/ mac app store 下载

**Comment by septs** [comment]
请将 apple-cdn-speed.report 上传

**Comment by fisherwei** [comment]
@septs 
[apple-cdn-speed.report.txt](https://github.com/gongjianhui/AppleDNS/files/197011/apple-cdn-speed.report.txt)

**Comment by yt1988** [comment]
@septs  已上
[apple-cdn-speed.txt](https://github.com/gongjianhui/AppleDNS/files/197583/apple-cdn-speed.txt)

**Comment by septs** [comment]
@gongjianhui

**Comment by gongjianhui** [comment]
@septs Received.

Sent from Outlook Mobile




On Thu, Mar 31, 2016 at 5:27 AM -0700, "Sept" <notifications@github.com> wrote:












@gongjianhui

**Comment by xinghusp** [comment]
删除配置文件中的 address=/itunes.apple.com/*** 了么，我在广西电信，不删掉这一行也是没办法下载app

**Comment by septs** [comment]
请尝试新的脚本
