### ISSUE TITLE
Mac OSX重置DNS緩存的命令在不同版本上是不一樣的

### ISSUE THREAD

**Issue by Bluelich** [gongjianhui/AppleDNS#41]
10.10.4 or later:
<kbd>sudo killall -HUP mDNSResponder</kbd>

10.10 ~ 10.10.3:
<kbd>sudo discoveryutil mdnsflushcache</kbd>

10.7 ~ 10.9.5:
<kbd>sudo killall -HUP mDNSResponder</kbd>

10.6 ~ 10.6.8:
<kbd>sudo dscacheutil -flushcache</kbd>

**Comment by sunsan05** [comment]
OSX 10.12 Sierra
sudo killall -HUP mDNSResponder

**Comment by Bliners** [comment]
CleanMyMac 的维护里面有刷新DNS缓存
