### ISSUE TITLE
同样的配置在iOS无法工作，但在Mac os正常

### ISSUE THREAD

**Issue by lix119** [gongjianhui/AppleDNS#5]
1、配置如下：
[Host]
iosapps.itunes.apple.com = 183.134.9.60
streamingaudio.itunes.apple.com = 183.134.9.60
aod.itunes.apple.com = 183.134.9.60
osxapps.itunes.apple.com = 183.134.9.60
client-api.itunes.apple.com = 184.87.97.50 
2、我确定没有其它有关apple的配置，全部走direct
3、mzstatic.com 的我个人觉得速度还能接受，就没加了
4、仔细观察log，还新发现了一个se2.itunes.apple.com
5、Mac os正常播放时的访问顺序截图如下
<img width="541" alt="2016-02-20 12 27 17" src="https://cloud.githubusercontent.com/assets/4980672/13181957/7731c2d4-d76a-11e5-901c-6457aa70c58e.png">

**Comment by gongjianhui** [comment]
1.删除除 iosapps aod streaming audio osxapps 之外其他域名重试。
4.这个以后会加入

**Comment by lix119** [comment]
补充，se2.itunes.apple.com在iOS establishing connection平均为450ms，transferring 100000ms，网络是浙江电信，wifi

**Comment by gongjianhui** [comment]
这个域名解析到了 Apple 自有服务器，都在美国，所以 AppleDNS 对该域名无效。
