### ISSUE TITLE
(p32-)buy.itunes.apple.com这些老连接被重置怎么办啊？有时候登入登出帐户也会显示无法连接？

### ISSUE THREAD

**Issue by doio** [gongjianhui/AppleDNS#50]
如题，这些问题怎么办啊？

**Comment by gongjianhui** [comment]
请问你是否在 DNSMASQ 中配置了 AppleDNS？如果是，回去仔细看 README。

**Comment by doio** [comment]
你好，py生成的里面确实有一条itunes.apple.com，我删了，虽然现在不会立刻提示网络中断，但是过一会还是会提示，也许最近苹果服务器抽风？？o(╯□╰)o

**Comment by doio** [comment]
大多时候不行，有时候行，好奇怪

**Comment by 2788897518** [comment]
校园网运营商是奇葩的CERNET，请问该选择哪个脚本？
