### ISSUE TITLE
请问为何去掉了 mzstatic.com 呢

### ISSUE THREAD

**Issue by cielpy** [gongjianhui/AppleDNS#53]
广东联通电信下载 App 都是用的这个 CDN，目前脚本生成的配置里并没有这个域名的规则

**Comment by gongjianhui** [comment]
mzstatic.com 一般情况下是图片服务器。

**Comment by cielpy** [comment]
这样啊，谢谢

-- 
Kevin Guo
Sent with Airmail

On 2016年4月20日 at 下午2:27:00, 宫剑辉 (notifications@github.com) wrote:

mzstatic.com 一般情况下是图片服务器。

**Comment by gongjianhui** [comment]
App Store App 下载使用的是 iosapps.itunes.apple.com
Mac App Store App 下载使用的是 osxapps.itunes.apple.com
