### ISSUE TITLE
校园网的运营商是CERNET，请问该选用哪个脚本？

### ISSUE THREAD

**Issue by 2788897518** [gongjianhui/AppleDNS#55]
如题，不是联通也不是电信...

**Comment by HeavenlyKing** [comment]
测试了一下各个脚本的结果，电信稍微快一些。不过Apple music 下载还是不行，时好时不好。总的来说，加速不定，有时候还是不开比较快。

**Comment by 2788897518** [comment]
嗯，三个我都跑了一遍，联通电信差不多都是50m，移动最差 100+

**Comment by 2788897518** [comment]
校园网下还真是 有时候开了还没有不开快

**Comment by HeavenlyKing** [comment]
现在体验最好的方式还是ipv6的dns加速，一直很快，然而只能电脑使用。不过我在寝室通过电脑发Wi-Fi给iPhone iPad使用，都不会卡，十分流畅。如果想尝试某度搜奶齿校园网ipv6 host

**Comment by gongjianhui** [comment]
在国际出口足够好的情况下，可以尝试 AppleDNS International https://gist.github.com/gongjianhui/823be8fcc23cc178547a5c2dcdd173ba

**Comment by 2788897518** [comment]
@gongjianhui 表中的地址还需要先ping一下吗？
