### ISSUE TITLE
会导致 Mac App Store 无法下载应用的问题

### ISSUE THREAD

**Issue by chengluyu** [gongjianhui/AppleDNS#56]
在 Mac App Store 中下载应用会出现提示“无法验证产品分发文件。它可能已损坏或尚无签名。”

删除添加的 hosts 文件、刷新 DNS、清除 Mac App Store 缓存、进入安全模式和重置 Mac App Store 均无效。

**Comment by chengluyu** [comment]
附：根据少数派文章下的某条评论，用 Time Machine 恢复可以解决问题。

**Comment by Patricsk** [comment]
删除hosts 重置dns缓存 重启 可解决

On Tue, Apr 26, 2016 at 3:34 PM Cheng Luyu <notifications@github.com> wrote:

> 附：根据少数派文章下的某条评论，用 Time Machine 恢复可以解决问题。
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gongjianhui/AppleDNS/issues/56#issuecomment-214654439>
>
-- 
—


南京理工大学紫金学院
邹伟铖
电话:  18550397790
邮箱：nono.z14c@gmail.com
地址：南京市栖霞区文澜路89号 210046

**Comment by chengluyu** [comment]
重复：删除添加的 hosts 文件、刷新 DNS、清除 Mac App Store 缓存、进入安全模式和重置 Mac App Store 均无效。

**Comment by chengluyu** [comment]
只能 Time Machine 解决，昨天花了一个小时恢复后解决。

**Comment by yulhun** [comment]
新疆地区这边apple cdn很少，速度起不来 能不能在看看。

**Comment by stirp** [comment]
我擦，我这个问题中招已经很久了，没有意识到是appleDNS的问题，刚刚试过了，删除添加的 hosts 文件、刷新 DNS、清除 Mac App Store 缓存 均无效，就差 进入安全模式和重置 Mac App Store了

time machine要还原到好久前呢，这可咋整啊！

**Comment by stirp** [comment]
而且不影响新程序安装，只影响期间更新的程序，现在它们卸载了也装不回来。求解啊！Time Machine只能回到太久远的过去，损失太大！ @Patricsk

**Comment by stirp** [comment]
换了国家的Apple ID，购买另一个国家的同一个App（已先卸载）也失败了。

@chengluyu 你知道这个App的信息应该会保存在系统的什么位置么？方便Time Machine恢复某个目录也行啊。

**Comment by stirp** [comment]
好消息是：补救措施可以更简单。

我创建了一个新用户，使用了同一个Apple ID，升级，没有问题。

既然如此，说明这个阻止升级的文件一定在用户目录下，于是换回原来的账户，删除~/Library/Caches目录下的所有子目录，升级、安装都丝般顺滑了，problem solved。

**Comment by chengluyu** [comment]
@stirp 很可惜……我已经 Time Machine 恢复了……

**Comment by bao3** [comment]
注意，这个问题确实会发生，我也发生了，即使去除 Hosts 相关以及  sudo killall -HUP mDNSResponder 重新刷新 DNS 也不能解决，重启也不行，隔几天也不行。唯一可以行的就是按照楼上的说法，删除 cache 重建。

非常危险！！！

**Comment by cuteguy** [comment]
换个wifi试试。先连接自己手机热点试试。

**Comment by saonian** [comment]
> 好消息是：补救措施可以更简单。
> 
> 我创建了一个新用户，使用了同一个Apple ID，升级，没有问题。
> 
> 既然如此，说明这个阻止升级的文件一定在用户目录下，于是换回原来的账户，删除~/Library/Caches目录下的所有子目录，升级、安装都丝般顺滑了，problem solved。

我试了，不管用

**Comment by saonian** [comment]
连手机热点没问题了，升级正常。应该是公司网络环境问题。

**Comment by lujinxin** [comment]
> > 好消息是：补救措施可以更简单。
> > 我创建了一个新用户，使用了同一个Apple ID，升级，没有问题。
> > 既然如此，说明这个阻止升级的文件一定在用户目录下，于是换回原来的账户，删除~/Library/Caches目录下的所有子目录，升级、安装都丝般顺滑了，problem solved。
> 
> 我试了，不管用

我也试了，不行。。。

**Comment by Green-Wood** [comment]
> 好消息是：补救措施可以更简单。
> 
> 我创建了一个新用户，使用了同一个Apple ID，升级，没有问题。
> 
> 既然如此，说明这个阻止升级的文件一定在用户目录下，于是换回原来的账户，删除~/Library/Caches目录下的所有子目录，升级、安装都丝般顺滑了，problem solved。

我今天试过了，想要下载magnet，但是还是不行。。。。

**Comment by Green-Wood** [comment]
> > 好消息是：补救措施可以更简单。
> > 我创建了一个新用户，使用了同一个Apple ID，升级，没有问题。
> > 既然如此，说明这个阻止升级的文件一定在用户目录下，于是换回原来的账户，删除~/Library/Caches目录下的所有子目录，升级、安装都丝般顺滑了，problem solved。
> 
> 我今天试过了，想要下载magnet，但是还是不行。。。。

刚刚把ss改成了全局模式，就可以正常下载了。。。。神秘啊

**Comment by oomheap** [comment]
> > > 好消息是：补救措施可以更简单。
> > > 我创建了一个新用户，使用了同一个Apple ID，升级，没有问题。
> > > 既然如此，说明这个阻止升级的文件一定在用户目录下，于是换回原来的账户，删除~/Library/Caches目录下的所有子目录，升级、安装都丝般顺滑了，problem solved。
> > 
> > 
> > 我今天试过了，想要下载magnet，但是还是不行。。。。
> 
> 刚刚把ss改成了全局模式，就可以正常下载了。。。。神秘啊

实测可行👍
