### ISSUE TITLE
既然开源了就放心给大家用吧,搞的这么麻烦

### ISSUE THREAD

**Issue by lifetin** [gongjianhui/AppleDNS#58]
既然开源了就放心给大家用吧,搞的这么麻烦

说一下我用的经过吧
不懂python,然后在电脑上搜一下个出了.执行命令,提示失败
重新下载一个3.3的,执行,又提示必须要3.4以上才能用.
又去找了个3.4的.最后才弄上.
前前后后花了1个半小时.这真是折腾人
既然分享了,而且技术这高么.何不必弄批处理呢?不是所有人都会python的.

**Comment by rampageX** [comment]
你为何不用**批处理**写一个来造福大家？

**Comment by HeavenlyKing** [comment]
每个地方的最优的dns是不一样，如何批处理？自己动手不行，能不能别怪别人，而且为什么自己不在Github上搜索呢？有一个图形化的程序提供，自己不找还怪别人？

**Comment by lifetin** [comment]
不是手动不行,是太费时间了.不是每个程序员都有python环境,都会python的.
给你建议是支持你,没有敢怪你.只是说想是否能简化使用者的流程.使用起来简单.快捷.明白吗?

**Comment by septs** [comment]
@lifetin https://github.com/gongjianhui/AppleDNS/tree/old 没让你一个一个手动测试 都自动化了

**Comment by HeavenlyKing** [comment]
你只是少数，不会有人为了少数人而做一些并不是很有意义的事。作为一个开源项目，谁有想法谁把自己的想法实现贡献出来，你觉得这样麻烦，你可以做一个图形化的程序，没有人反对。而不是你觉得烦，还要求别人给你做东西。因为在别人看来，这一点都不烦。
