### ISSUE TITLE
速度并不稳定

### ISSUE THREAD

**Issue by 2788897518** [gongjianhui/AppleDNS#60]
系统为ios，校园网环境下，配置完成后，清空dns缓存，重启，第一次下载podcast能达到满速，下载第二个时候又变回龟速了，向作者请教原因和解决方法。

**Comment by gongjianhui** [comment]
请问您下载的是什么？是播客的音频文件吗？

**Comment by 2788897518** [comment]
是的

**Comment by gongjianhui** [comment]
Podcasts.app 里面的播客音频文件由播客方托管。
