### ISSUE TITLE
音乐视频似乎没有解析正确

### ISSUE THREAD

**Issue by sarkrui** [gongjianhui/AppleDNS#63]

**Comment by gongjianhui** [comment]
Music Video 一般是 aodp.itunes.apple.com

**Comment by sarkdavidson** [comment]
未添加修改Hosts
```
64 bytes from 122.228.205.50: icmp_seq=47 ttl=54 time=45.993 ms
^C
--- app.dlmix.ourdvs.com ping statistics ---
48 packets transmitted, 48 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 37.406/54.666/374.657/62.726 ms
```
根据AppleDns解析结果
修改hosts
183.57.28.211 aod.itunes.apple.com
尝试
183.57.28.211 aodp.itunes.apple.com

```
64 bytes from 183.57.28.211: icmp_seq=37 ttl=58 time=19.756 ms
^C
--- aodp.itunes.apple.com ping statistics ---
38 packets transmitted, 38 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 17.684/24.731/56.048/8.912 ms
```
打开MV速度的确提高了，但画质大概只有360P，广东电信50兆，油管跑1080P都没问题，本地网络带宽是足够的。

**Comment by lingaoyi** [comment]
17.253.85.202 我广州电信，用这个感觉还行。

**Comment by sarkdavidson** [comment]
潮汕这边 ping 17.253.85.202 
`round-trip min/avg/max/stddev = 140.157/145.175/153.169/3.451 ms`
ping 183.57.28.211
`round-trip min/avg/max/stddev = 16.905/20.086/44.192/6.256 ms`
