### ISSUE TITLE
用这个工具测试时路由器翻着墙会有影响吗？

### ISSUE THREAD

**Issue by bearcolin** [gongjianhui/AppleDNS#64]
如题，我在 Merlin 路由器用 Shadowsocks 设置了境外IP翻墙，在开着ss和没开的时候，最后生成的配置文件不太一样。

开着SS翻墙的时候最后生成的配置里多了 API-HK-Akamai-2-AMRadio 项，没翻墙的时候没AMRadio这项。

另外 API-2-ChinaCache 和 API-HK-Akamai-1 这两部分的IP也不一样。

所以我应该用开着 SS 还是关着 SS 的时候测的结果？

谢谢！

**Comment by gongjianhui** [comment]
建议您关闭 SS 后测试
