### ISSUE TITLE
手机访问的问题

### ISSUE THREAD

**Issue by fentensoft** [gongjianhui/AppleDNS#66]
上海电信，路由器OpenWRT系统，用ChinaNet配置，直接通过路由器设置dns解析。使用时发现设置->App Store->查看Apple ID点不开，无法加载

**Comment by gongjianhui** [comment]
请问你在配置 dnsmasq 时是否删除了 itunes.apple.com 这一行？

**Comment by fentensoft** [comment]
抱歉是我忽略了，删掉之后正常了，多谢！
