### ISSUE TITLE
iTunes 无法验证服务器“p35-buy.itunes.apple.com”的身份。

### ISSUE THREAD

**Issue by akimotoakira** [gongjianhui/AppleDNS#7]
iTunes 无法验证服务器“p35-buy.itunes.apple.com”的身份
此服务器的证书无效。您可能正在连接一个假装是“p35-buy.itunes.apple.com”的服务器，您的机密信息可能会有风险。您仍想连接该服务器吗？

设置 host 以后 iTunes 出现此问题？

**Comment by gongjianhui** [comment]
无论如何都不要与证书不正确的服务器连接，稍后我来跟进。

**Comment by gongjianhui** [comment]
List 中并没有和 p**-buy 相关域名的项目，请问你是否改动了其他规则？另外您 Hosts 是在什么时候设置的？

**Comment by gongjianhui** [comment]
请问您使用什么操作系统，以及使用什么地区的哪家电信运营商。

**Comment by akimotoakira** [comment]
上海电信 Mac OS X 10.11.4 Beta (15E61b)
刚刚设置的 有上海的我填了上海 没上海的我填的香港
一加进 Hosts 打开 iTunes 进 Apple Music 新内容首页就会出现证书问题
一删掉 Hosts 重开就好了……

**Comment by akimotoakira** [comment]
等下 我试着把 ss 关掉再加 Hosts 好像也没问题

**Comment by gongjianhui** [comment]
我在很多中网络环境下都测试过，最多会出现无法打开，没出现过证书错误的问题，请检查你的代理软件黑名单中是否包含 Apple 的域名。

**Comment by akimotoakira** [comment]
似乎是我 DNS 的问题 换了个 DNS 就没出现证书错误了

**Comment by gongjianhui** [comment]
好的，之后有什么问题可以再找我。

**Comment by smartguy9999** [comment]
我也发生同样类似的问题。之后还出现“iTunes发生未知错误504”。现在根本无法从App Store里下载任何软件了。

**Comment by smartguy9999** [comment]
我把SS关闭了，也解决这个问题了。可是，你的这个加速，我是放在SS的DNSMaq里的，关闭了SS就无法享受你这个加速了。

**Comment by frank4565** [comment]
同样有这个问题。用的是 dnsmasq，原因是`address=/itunes.apple.com/<ip address>`，这行会将所有以 itunes.apple.com 结尾的域名都解析到这个 ip address 上。删掉这行或者把所有出问题的域名都显示写上真正的 ip address 或显示指定 DNS server 可解决。

**Comment by gongjianhui** [comment]
这货还有泛解析？惊了。

**Comment by gongjianhui** [comment]
@akimotoakira 请问您使用的配置方式是什么？

**Comment by akimotoakira** [comment]
果然是梅林的问题~今天重新配置后已经好了
话说按今天的步骤来 导出的配置已经是测速后最优的结果了是吗？

**Comment by gongjianhui** [comment]
@akimotoakira 延迟最低，可能并不是下载速度最快的，但这是目前的最优解。
