### ISSUE TITLE
什么时候可以支持icloud音乐资料库

### ISSUE THREAD

**Issue by TomatoFryEggs** [gongjianhui/AppleDNS#76]
有些歌曲applemusic没有，但还好apple 提供了icloud音乐资料库，但同步起来太慢。

**Comment by S4MUELSKULL** [comment]
好在我的 Surge 里常年 Proxy iCloud.com 😃

**Comment by zjcnew** [comment]
对 iCloud 相关服务的加速，请查看 ProxyConfig.md 文件，这个硬是没看懂！

**Comment by gongjianhui** [comment]
iCloud 音乐资料库的音频及封面文件使用 s3-external-1.amazonaws.com，请代理该域名。
