### ISSUE TITLE
有没有icloud的加速

### ISSUE THREAD

**Issue by palese** [gongjianhui/AppleDNS#8]
ios9云备份一直不成功

**Comment by gongjianhui** [comment]
将 amazonaws.com 加入代理软件的列表中，将代理彻夜打开。

**Comment by palese** [comment]
谢谢

**Comment by palese** [comment]
苹果用的是亚马逊的服务啊

**Comment by gongjianhui** [comment]
*.icloud.com, *.icloud-content.com, *.apple.com 17.0.0.0/8 除特殊情况下（如 Apple Music 的 aod/streamingaudio.itunes.apple.com）都不要进入代理软件的黑名单中。

**Comment by palese** [comment]
那几个没入代理，今天早上莫名奇秒就备份成功了

**Comment by gongjianhui** [comment]
由于 iOS 的特性，我也不知道为什么。

**Comment by palese** [comment]
就是莫名奇秒的很，几个月都没备份成功了，今天早上手动试了一下，居然还成功了，之前手动试过无数回
