### ISSUE TITLE
导致Apple Music电台功能无法使用？

### ISSUE THREAD

**Issue by Waynehuu** [gongjianhui/AppleDNS#80]
改了hosts之后无法通过某首歌曲创建电台，“广播”tab下面的电台也都无法播放。不改hosts的时候两项功能均能正常使用。

**Comment by hankbao** [comment]
似乎是有这个问题。在路由上开启 AppleDNS 后尝试播放 Apple Music 上的任意电台，都会提示“无法启动电台”。
