### ISSUE TITLE
果然还是有效果~ 已支磁，不过提个小问题。

### ISSUE THREAD

**Issue by MassenEvan** [gongjianhui/AppleDNS#9]
测试了之后效果还不错！看到文案已笑翻，遂支磁 CNY 66. 再接再厉哈！
不过，有一个问题是，在 App Store 下载 App 的时候，如果输入 Apple ID 密码之后，第一次会无缘无故出现错误提示，如图：http://ww1.sinaimg.cn/large/0060lm7Tgw1f20xfo0zygj30ku112grp.jpg

然后点击再试一次，重新输入 Apple ID 密码就奇迹般的可以了。每个 App 都是这样。不知道是哪个环节的问题。

虽然问题不大，但强迫症你懂的。

我的 IP 配置是这样的。（地理位置：重庆）
[Host]
# AppleDNS Project
# https://github.com/gongjianhui/AppleDNS/

iosapps.itunes.apple.com = 119.84.70.20
streamingaudio.itunes.apple.com = 119.84.70.20
aod.itunes.apple.com = 119.84.70.20

radio.itunes.apple.com = 23.13.185.169
radio-services.itunes.apple.com = 23.13.185.169
radio-activity.itunes.apple.com = 23.13.185.169

search.itunes.apple.com = 23.198.133.66

init.itunes.apple.com = 119.84.69.26
itunes.apple.com = 119.84.69.26

play.itunes.apple.com = 222.211.64.122
upp.itunes.apple.com = 222.211.64.122
client-api.itunes.apple.com = 222.211.64.122
su.itunes.apple.com = 222.211.64.122
se.itunes.apple.com = 222.211.64.122

**Comment by gongjianhui** [comment]
AppleDNS 为了安全，几乎没有涉及任何和帐号信息有关的服务器，测试中确实出现过这种情况，我也没有分析出来什么。
